### ISSUE TITLE
Add ability to map fields to onPremisesExtensionAttributes

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#11]
Please add an option to map fields to onPremsisesExtensionAttributes

https://docs.microsoft.com/en-us/graph/api/resources/onpremisesextensionattributes?view=graph-rest-1.0

**Comment by RobTrehy** [comment]
This will be available with the next Staff Directory App update (version 1.0.6)

All default fields, apart from username, will be able to be mapped with any available Azure field.
Toggle fields (On Leave, Cover, Senior) will convert a 'true' or 'yes' value into the field being toggled on, any other value will toggle the field off.
