### ISSUE TITLE
Hide users

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#13]
To have the ability to exclude/hide users from showing in the directory.

**Comment by RobTrehy** [comment]
This will be available in the next Staff Directory App update (version 1.0.6)

- Setup Azure sync as normal, and allow all users to be synced
- If people/accounts are synced that you do not require, go to Manage Staff and select the user
- A new option will appear
![image](https://user-images.githubusercontent.com/13102009/159915829-5c02bbcf-715e-4c8c-b498-2d517a85000e.png)
Note: This option only appears for users who have been created by a Microsoft Azure sync.
- Clicking this will disassociate the user with Azure and add them to the "Do not sync" list
- You can then choose to either edit the user, or delete them

You can see the "Do not sync" list in App Settings > Azure Integration
![image](https://user-images.githubusercontent.com/13102009/159915672-ba1e1dbc-ca86-4e34-893a-af487215fbe0.png)
Click the 'X' mark if you later wish to remove a user from the "Do not sync" list.
