### ISSUE TITLE
Remove Senior or rename option

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#14]

**Comment by RobTrehy** [comment]
You can hide any fields that you do not require in the App Settings - as of Staff Directory version 1.0.5

[See Documentation](https://docs.getwebapps.uk/v/apps/staff-directory/app-settings/select-fields#employment-details)

**Comment by lehsaclarkson** [comment]
This issue was to do with the unknown toggle at the bottom of the photo library called Staff member is senior. It was unsure what this was.

**Comment by RobTrehy** [comment]
You can turn off the field so that it does not display, see the link above for how to do so

**Comment by lehsaclarkson** [comment]
But what is it for?




Mr A Clarkson

Applications Delivery Manager - IT Services



Lady Eleanor Holles

Hanworth Road, Hampton, Middlesex TW12 3HF

Telephone: 020 8979 1601

Twitter: @***@***.***>

Web: www.lehs.org.uk<http://www.lehs.org.uk/>



[Lady Eleanor Holles_RGB]

________________________________

**Comment by RobTrehy** [comment]
At the moment, nothing.

In the future it will be a customisable banner on certain display options. Similar to how the "Head of Department" banner current displays on the 3D Flip Photo Grid display mode.

It could be used to highlight company directors or other senior staff.
