### ISSUE TITLE
Embeded Photo Directory departments don't display

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#16]
When a photo directory department is embedded from the photo library it doesn't show on the page. 

Set as auth users

**Comment by RobTrehy** [comment]
You mean when you've created a view that is set to show just one department?
I'd be interested to see your view settings, as this works fine here.

![image](https://user-images.githubusercontent.com/13102009/158783384-078adefb-d7f6-4d5d-a2c2-da06014f0488.png)

Produces: [https://check.getwebapps.uk/apps/StaffDirectory/view/HJJclDqCbj](https://check.getwebapps.uk/apps/StaffDirectory/view/HJJclDqCbj)

**Comment by lehsaclarkson** [comment]
![image](https://user-images.githubusercontent.com/12826304/158792714-dd4c18a4-93c1-491c-9751-970b710ebb36.png)
![image](https://user-images.githubusercontent.com/12826304/158792841-fb1ac406-9c27-4053-94e4-6efb131483b8.png)
![image](https://user-images.githubusercontent.com/12826304/158793050-3a96c71c-c0b9-4dbf-9249-19374d5dc11b.png)

Error messages like the following: 
{message: "CSRF token mismatch."}
message: "CSRF token mismatch."
{message: "Unauthenticated."}
message: "Unauthenticated."

**Comment by RobTrehy** [comment]
Thanks, I've been able to reproduce now. I'll investigate.

**Comment by RobTrehy** [comment]
Closing as resolved
