### ISSUE TITLE
Viewing the Department list on Staff Directory

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#23]
When you view the department list of the Staff Directory this is not in Alphabetical order.

**Comment by lehsaclarkson** [comment]
On a previously created view the Sort order is still not Alphabetised. 
![IMG_1961](https://user-images.githubusercontent.com/12826304/166677095-91f4bcf2-4b82-4311-824b-f7ff03feacdf.jpg)

**Comment by RobTrehy** [comment]
Fixed with [9290f08](https://github.com/RTWA/App-Staff_Directory/commit/9290f087849295282054076a77b763cafb6392b0) - In next App update
