### ISSUE TITLE
Some Sub Departments do not appear under the correct parent department

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#26]
We have noticed that some departments do not show under the parent department by default. 

Example 
Science only contains Physics and Technicians

**Comment by RobTrehy** [comment]
Suspect this is related to a sync prior to my fix as I cannot replicate this.
I'll look into this on a remote session at some point.

**Comment by RobTrehy** [comment]
Extra fix required:
masterController.php - Add whereNull

![image](https://user-images.githubusercontent.com/13102009/166815018-636f34dd-0949-44a0-9a22-1de840e1f2b7.png)

and >= 1

![image](https://user-images.githubusercontent.com/13102009/166815276-860cd0a9-1877-4760-9c90-f1a98471f165.png)

Created hotfix on your server, will be included in the next App update too.
