### ISSUE TITLE
Old Departmenets are not deleting after a re-sync of Azure

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#27]
I have noticed that some of the old groups do not remove themselves when there is no one in the group. 
Either can these be removed from the database or hidden if there are no members of the group. 

Example
U4 Students
Junior School Head

**Comment by RobTrehy** [comment]
You can delete any departments that are no longer required.

Go to App Settings, Select the department from the dropdown list, and then click Delete Department, followed by Are You Sure?

**Comment by lehsaclarkson** [comment]
I’ll go through departments and remove the old ones. Can departments that have 0 members not appear in the departments list of the staff directory?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
