### ISSUE TITLE
Deleting a record in staff Directory

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#29]
When you delete a record from the Staff Photo Directory it doesn't refresh and it still shows the same record even if it has been deleted.

**Comment by RobTrehy** [comment]
This was fixed with [d8dfea0](https://github.com/RTWA/App-Staff_Directory/commit/d8dfea0e9affe3c59872832bbc55b8feb1ada07e)

Please await App update
