### ISSUE TITLE
Staff unable to view the Photo Directory

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#30]
We are having a problem with the staff being able to view the Staff Directory. It currently returns an error of 

Sorry you do not have access to view this information. 
I'm currently unable to find where we allow the Staff Group to gain access to the Staff Directory
![No Access](https://user-images.githubusercontent.com/12826304/165332989-ddba5353-f457-412d-b1f7-3471ca7a2d01.png)

**Comment by RobTrehy** [comment]
Note - this affects the default All Staff view, creating a custom view and allowing all groups access to it works OK.

**Comment by lehsaclarkson** [comment]
This hasn't fixed the problem. the URL /apps/StaffDirectory/view/all still doens't display.

**Comment by RobTrehy** [comment]
Will investigate your local install in a remote session

**Comment by lehsaclarkson** [comment]
Fixed
