### ISSUE TITLE
A New member of staff is displaying at the bottom of the list in the All Staff View

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#31]
In the all staff view a new member of staff has started and she is appearing at the bottom of the list of staff rather than the top. 

I've checked her Start Date and it states the correct start date.

**Comment by RobTrehy** [comment]
I've been unable to replicate this issue - I'll contact you for a remote session at some point :)

**Comment by RobTrehy** [comment]
Installing updates creates duplicate entries in the azure_map_fields App table
This is then setting `startDate` to `do_not_sync`
