### ISSUE TITLE
Selecting by Department

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#42]
Can the focus be changed on the drop down in the Staff Directory so that when you have selected a department and want to select another one you don't have the scroll down the list to find where you previously were. 
It's a pain to have to keep scrolling down the department list all the time

**Comment by RobTrehy** [comment]
Unfortunately not- this is due to the implementation of the select list.

The select list is searchable though, so you could type the name of the department and the list will filter.
