### ISSUE TITLE
Staff Directory - Manage Views - Updating Table Fields

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#47]
When you update the Table Fields in the manage views it does not update the View in the Embed to reflect this change

**Comment by RobTrehy** [comment]
I have been unable to replicate this.

**Comment by RobTrehy** [comment]
Is this one still an issue, I can't replicate it at all?

**Comment by lehsaclarkson** [comment]
I don't think this is a bug now and I haven't seen it do this lately.
