### ISSUE TITLE
Embedding Blocks into MS Sharepoint site returns that the iframes are not compatiable

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#51]
This is the error I get I try and embed Webapps to a sharepoint site

![image](https://user-images.githubusercontent.com/12826304/173872902-834ef921-b3e6-4fcc-ae16-aed26e334ead.png)

**Comment by RobTrehy** [comment]
What happens if you remove the comment?
So that it is just the `<iframe [...]></iframe>` part

**Comment by lehsaclarkson** [comment]
[Image.jpeg]

This is what it says. I've found that it doesn't like the style: and wants everything to be in-line with the iFrame.

________________________________

**Comment by RobTrehy** [comment]
Ah, I've just spotted it. 
The style tag says `width=100%`, it should be `width:100%`

**Comment by lehsaclarkson** [comment]
Yes. This is correct. When changing this to be width:100% it works as expected.

**Comment by RobTrehy** [comment]
Fixed in v1.1.0 of App - just released

**Comment by lehsaclarkson** [comment]
Good spot. Yes that now works.
________________________________
