### ISSUE TITLE
Wrong photograph showing for the wrong person when a user is searched for

### ISSUE THREAD

**Issue by mrWhitton** [RTWA/App-Staff_Directory#54]
When you search for a user the staff directory is displaying the wrong picture for the person selected from the search. This only occurs when you search for users. It also can be a different picture if you search more than once. 

Examples have been emailed to the support email address.

**Comment by RobTrehy** [comment]
Thank you, I have received the screenshots. 

This, I believe is due to the lazy loading of the images. 
Do the photos change after a short while?

I will investigate.

**Comment by RobTrehy** [comment]
This was resolved in App version 1.1.7

**Comment by mrWhitton** [comment]
No. They never do refresh. I left them for about 5mins.
I’m guessing this is more about optimisation.
Do you store the photographs in the DB as a blob or live pull them from
Azure on every request?

Andy
