### ISSUE TITLE
Selecting the new View

### ISSUE THREAD

**Issue by mrWhitton** [RTWA/App-Staff_Directory#60]
We are trying to create a new view under Staff Directory/Views. When we select the new View (ASM) it loads into a blank page with the following error in the console

<img width="555" alt="Screenshot 2022-09-16 at 13 51 39" src="https://user-images.githubusercontent.com/15094859/190642989-99220687-1e5c-457d-93f0-e3ca30e7e0ec.png">
<img width="1677" alt="Screenshot 2022-09-16 at 13 52 16" src="https://user-images.githubusercontent.com/15094859/190643340-386dd19b-3023-4e43-9be5-2f424a0189e3.png">

**Comment by mrWhitton** [comment]
Sorry I'm unable to see anything in network which points to an error.

**Comment by RobTrehy** [comment]
Sorry, I wasn't clear. It'll have returned at 200 status, as the return is fine.

The full request URI will be: https://{webapps_url}/apps/StaffDirectory/view/{view.publicId}

**Comment by RobTrehy** [comment]
Fixed in App update. Invalid JSON in view build.
