### ISSUE TITLE
Feature Requst: Move Create New View

### ISSUE THREAD

**Issue by mrWhitton** [RTWA/App-Staff_Directory#61]
Can the "Create new view" be moved so it doesn't sit in the My Views section. When you have a lot of views it goes to the bottom and can't be found as easily. 
<img width="1363" alt="Screenshot 2022-09-16 at 13 59 32" src="https://user-images.githubusercontent.com/15094859/190645758-b5b36b8f-bc63-46ba-a01f-fd635fbb3487.png">

**Comment by RobTrehy** [comment]
In next App release
