### ISSUE TITLE
Formatting for selectors for Views

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#67]
The second selector (Display department selectors and name search?) doesn't show correctly when creating and changing a view.

**Comment by RobTrehy** [comment]
Is this the issue due to screen resolution?
Could you provide a screenshot to remind me please

**Comment by lehsaclarkson** [comment]
It's more a functionality issue. When you use the selector against a group of people the filter doesn't filter that group of people and just sorts them by alphabetic surname order. This only happens on a view.

**Comment by RobTrehy** [comment]
Then I think this was a duplicate issue, which should be resolve in Staff Directory version 1.1.9, released this morning. 
Please update and confirm :)

**Comment by lehsaclarkson** [comment]
I've just updated and the problem is still there.

**Comment by lehsaclarkson** [comment]
Actually it's fixed when in the preview but not when you use the URL in a new tab/window. Cache?

**Comment by RobTrehy** [comment]
Could well be a cache issue, I'm unable to replicate any issues with using the filters since the update.

**Comment by lehsaclarkson** [comment]
I have cleared all the cache but it hasn't made a difference. Let me know if you want to take a closer look to see if you can work out why this is not working right?

**Comment by lehsaclarkson** [comment]
It looks like it is fixed now. I just tried it again and it is filtering correctly.
