### ISSUE TITLE
Bug: Searching View Data by Name

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#72]
When using the Search by name on a table view if you type in a name (example) Andy. You get the correct person. If you delete the name and then type in another Name (Andrew) it doesn't return anyone (there are two other Andrew's). To get around this to you have to delete what is in the box completly (waiting to show all staff) and then type in the name again.

**Comment by RobTrehy** [comment]
This affects all view types, not just tables
