### ISSUE TITLE
Feature Request: Select fields displayed on 3D Flip Photo

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#73]
I would like to have the ability to add extra information to the Photo Directory like extra fields to the contact card. I would like to add the ability to add responsibilities to staff profiles. 
Is there any ability to be able to search for these. For example if you type in Charity it will return who is responsibility for Charity at the School. If I type in GDPR it will return all staff responsible for GDPR.

**Comment by RobTrehy** [comment]
A basic version of this will be available in the next App update
