### ISSUE TITLE
How to embed the Photo Directory

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/App-Staff_Directory#9]
I can't seem to work out how to embed the Photo Directory onto a page in an embed.
Is there a URL or a quick way to do this?

**Comment by RobTrehy** [comment]
I'll keep this issue open until I've created documentation for this app.


However, you can go to Manage Views, then select your View (either create one, or you can select the default All Staff view on the right). 
Once happy with the settings, you can then select "Use This View" to retrieve the embed code.

**Comment by RobTrehy** [comment]
Documentation for this app is [now live](https://docs.getwebapps.uk/v/apps/staff-directory/what-is-staff-directory)
